# action.yml
name: 'Chalice Extended Action python 3.8'
description: 'This Github action allows automated deployment of your Chalice application via Github Actions.'
author: 'Janfabian Fabriczek <janfabian@fabriczek.engineer> (Based on previous action of: Chris Oh <chris@5tigerjelly.com>)'
branding:
  icon: cloud
  color: yellow
runs:
  using: 'docker'
  image: 'Dockerfile'
